version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo
    ports:
      - "3200:3200"
  mimir:
    image: grafana/mimir
    ports:
      - "9009:9009"
